### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by kasium** [luismedel/tsid-python#1]
Would it be possible to add type hints to the project? I'm happy to contribute these

**Comment by luismedel** [comment]
I tried to add all type hints to the code but, please, feel free to add any missing hint you miss, sure.

**Comment by kasium** [comment]
Yes you are right 😄 But they are not exposed (meaning that e.g. mypy won't see them) unless in the distribution root there is a py.typed marker. Let me do a quick PR to add this.

And thanks a lot for your fast reply!

**Comment by luismedel** [comment]
I see. TBH, I didn't knew about the `py.typed` file.

Thank you!
