### ISSUE TITLE
Python version specifier is incorrect

### ISSUE THREAD

**Issue by insertjokehere** [luismedel/tsid-python#4]
Thanks for such a useful package! One issue I've noted while trying to use it; in your `pyproject.toml`, you specify that the package `requires-python` 3.7 or newer:

https://github.com/luismedel/tsid-python/blob/67233ac16e6cfa3e1dd3a550754e0d37ec9c750e/pyproject.toml#L5-L13

However, in `tsid.py`, you then use the `match` syntax that is not supported by Python versions older than 3.10:

https://github.com/luismedel/tsid-python/blob/67233ac16e6cfa3e1dd3a550754e0d37ec9c750e/src/tsidpy/tsid.py#L214-L229

**Comment by luismedel** [comment]
Thank you @insertjokehere! You're right.

I'm adding proper CI/CD steps to spot this in the future.
